trigger: 
- main

pool:
  vmImage: ubuntu-latest


steps:
  - checkout: self

  - script: |
      wget https://releases.hashicorp.com/terraform/1.12.2/terraform_1.12.2_linux_amd64.zip
      unzip terraform_1.12.2_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform version
    displayName: Install Terraform

  - script: |
      terraform version
    displayName: Terraform Version

  - task: AzureCLI@2
    displayName: 'Terraform Init'
    inputs:
      azureSubscription: 'terraform-dev'
      scriptType: bash
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      inlineScript: |
        echo "Logged into Azure"
        az account show
  
        export ARM_USE_OIDC=true
        export ARM_CLIENT_ID=$servicePrincipalId
        export ARM_TENANT_ID=$tenantId
        export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
        export ARM_OIDC_TOKEN=$idToken
  
        cd environments/dev
  
        terraform init