trigger: 
- main

pool:
  vmImage: ubuntu-latest



variables: 
- group: terraform-dev
- name: workingDirectory
  value: environments/dev
- name: serviceConnection 
  value: terraform-dev


stages:
  - stage: Validate
    displayName: Terraform Validation

    jobs:
      - job: Validate
        displayName: Terraform Checks

        steps:
          - checkout: self
        
          - template: templates/install-terraform.yml
        
          - template: templates/terraform-init.yml
            parameters:
              serviceConnection: 'terraform-dev'
              workingDirectory: 'environments/dev'
        
          - template: templates/terraform-fmt.yml
            parameters:
              workingDirectory: 'environments/dev'
        
          - template: templates/terraform-validate.yml
            parameters:
              workingDirectory: 'environments/dev'
        
          - template: templates/terraform-plan.yml
            parameters:
              workingDirectory: 'environments/dev'
              serviceConnection: 'terraform-dev'

  - stage: Deploy
    displayName: Deploy to Dev
  
    dependsOn: Validate
  
    jobs:
  
    - deployment: DeployDev
  
      environment: dev
  
      strategy:
        runOnce:
          deploy:
            steps:
  
            - checkout: self

            - template: templates/install-terraform.yml

            - template: templates/terraform-apply.yml
              parameters:
                serviceConnection: 'terraform-dev'
                workingDirectory: 'environments/dev'