trigger: 
- main

pool:
  vmImage: ubuntu-latest


variables: 
   workingDirectory: environments/dev
   serviceConnection: terraform-dev


steps:
  - checkout: self

  - template: templates/install-terraform.yml

  - template: templates/terraform-init.yml
    parameters:
      serviceConnection: ${serviceConnection}
      workingDirectory: ${workingDirectory}

  - template: templates/terraform-fmt.yml
    parameters:
      workingDirectory: ${workingDirectory}

  - template: templates/terraform-validate.yml
    parameters:
      workingDirectory: ${workingDirectory}